# Generated by Django 4.1.4 on 2022-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='surname',
            field=models.CharField(default='no', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familiares',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
